baseURL = 'https://alexn0tes.github.io/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = 'PaperMod'

[params]
  author = "ALex"
  # 是否在首页显示文章列表
  homeInfoParams.Title = "你好，欢迎来到我的博客 👋"
  homeInfoParams.Content = "这里记录技术笔记、生活与思考。"
